### ISSUE TITLE
Master issue for global event handling suggestions and improvements

### ISSUE THREAD

**Issue by andlabs** [andlabs/libui#326]
An assortment of suggestions to event handling. Codependent on #321 and #325.

- [ ] Instead of having a separate function for every event, have a single function and the event passed in as a constant (**maybe**)
- [ ] The ability to programmatically call an event handler for both events and menu actions; or alternatively, a way to specify that they should be called when programmatically changing something (**maybe**)
- [ ] Likewise, but for uiQuit() (**maybe**)
- [ ] Drop uiAreaHandler and switch to event callbacks for it, passing the data argument normally instead of extending the structure; or alternatively, having the data argument be part of uiAreaHandler itself (**maybe** for the latter)

This topic will be unlocked when I merge existing issues in.

**Comment by parro-it** [comment]
I recently discovered the way `libui-node` implements event handlers leaks memory. 
That's because I never properly cleanup events callbacks when control are destroyed. 

Trying to improve this stuff, I get stucked because I don't find a proper way to discover when a control is destroyed.

I would need one of these implemented in libui:

1) an onDestroy event fired by every control when they are destroyed.
or
2) a new `void* data` element on uiControl struct (this would allow me to implement previous event on C++ side)
