### ISSUE TITLE
cmake issues, please help fix it

### ISSUE THREAD

**Issue by andlabs** [andlabs/libui#93]
Mostly broken on Windows:

- [X] MinGW build - breaks on windres because it passes a stray `-D` that I have no idea where it comes from
- [X] MSVC shared - same issue
- [ ] MinGW build - includes CFLAGS in RC flags, which confuses windres into thinking `extern` is an input file because it includes `_UI_EXTERN`
- [X] MSVC shared - breaks on link because it tries to set up its own manifest file that conflicts with ours; I have no idea how to tell cmake not to do this
- [ ] MSVC shared - incremental building is unwanted but I don't see a way to turn them off
- [ ] MSVC shared - extra `/W3` (we pass `/W4`)
- [X] MSVC shared - libui.lib not placed in `out/` folder, so executables fail to link
- [X] MSVC shared - executables are linked with a bunch of extra system libraries; they should be linked to **none**
- [ ] MSVC static - extra `/W3` (we pass `/W4`)
- [ ] MSVC static - resources.res not placed in `out/` folder (should be libui.res)
- [ ] MSVC static - said resources.res is not linked with executables, meaning they fail to start due to comctl32.dll, and crash when accessing any of the dialog templates used

How would I get a MSVC toolchain build with a GNU makefile? `-G "Unix Makefiles"`? **Answer: Yes, if MinGW is not in %PATH%**

Untested:
- Linux 32-bit shared
- Linux 32-bit static
- other Unixes

**Any other suggestions to improve the CMake files are accepted here too. I'm pretty sure these files are NOT idiomatic and skirt cmake's capabilities that I don't know about, so...**

**Comment by kainjow** [comment]
You can try the "NMake Makefiles" generator, although I've never used it.

As for MinGW, I've always used a separate toolchain file, and passed that into CMake.

**Comment by FraGag** [comment]
> * MSVC shared 
>   * breaks on link because it tries to set up its own manifest file that conflicts with ours; I have no idea how to tell cmake not to do this

I faced a similar problem while making a CMake-based build system for Exodus, which had its own manifest as well. However, since Exodus uses Visual Studio projects, it already had to deal with the generated manifest (it could have been disabled, but that wasn't the case). Contrarily to what you're currently doing, the manifest is **not** included via a `.rc` file.

Visual Studio offers an option to **merge** a custom manifest with the generated manifest, using the Windows SDK's [Manifest Tool](https://msdn.microsoft.com/en-us/library/aa375649%28v=vs.85%29.aspx). [Here's how I solved this in the CMake script.](https://bitbucket.org/FraGag/exodus/commits/34ce69207c481d3648608d2513ed35ab2b58f6af?at=default#LExodus/CMakeLists.txtT77) Note that the `#1` at the end of the command line is the resource ID. As you're using `ISOLATIONAWARE_MANIFEST_RESOURCE_ID`, which is defined as `2`, in your resource script, you would have to pass `#2` instead.

However, after doing this, I added support for MinGW, which doesn't generate a manifest, so in order to have the same manifest in the application, no matter which toolchain the user chose, I [disabled manifest generation](https://bitbucket.org/FraGag/exodus/commits/c2ed6dd288f4a8924584ecfbfed036761d5f7aec?at=default#LExodus/CMakeLists.txtT77) and [added the stuff from the generated manifest to the custom manifest](https://bitbucket.org/FraGag/exodus/commits/c2ed6dd288f4a8924584ecfbfed036761d5f7aec?at=default#chg-Exodus/app.manifest) (your generated manifest may be different from this!). (BTW, don't pay attention to the `.props` files in that commit, they're for the MSBuild-based build system.)

**Comment by andlabs** [comment]
Wow, that single line in that last link alone actually did it! Thanks!

That leaves incremental linking, though...

**Comment by andlabs** [comment]
Also @kainjow could you repost your thing about shared libraries? Thanks.

**Comment by andlabs** [comment]
Okay, so now I have

```cmake
# 30 may 2016
cmake_minimum_required(VERSION 2.8.12)

# set up our configurations
set(CMAKE_CONFIGURATION_TYPES Debug Static Release ReleaseStatic)
# we load the variables after calling project()
# default to Debug if no configuration specified
if(NOT CMAKE_BUILD_TYPE)
	# the CACHE FORCE is necessary for this to work properly
	set(CMAKE_BUILD_TYPE Debug CACHE STRING "Build type; one of: Debug Release Static ReleaseStatic" FORCE)
endif()
# and save whether this is shared in a variable
if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
	set(_SHARED TRUE)
elseif(${CMAKE_BUILD_TYPE} STREQUAL "Release")
	set(_SHARED TRUE)
endif()

# and we need to set this up prior to project() too
set(CMAKE_OSX_DEPLOYMENT_TARGET "10.8")

project(libui)

# TODO can this be above the project()?
if(WIN32)
	if(NOT MSVC)
		if(_SHARED)
			message(FATAL_ERROR
				"Sorry, libui for Windows cannot be built as a DLL with MinGW. You will need to either build as a static library or build with MSVC.")
		endif()
	endif()
endif()

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/out")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/out")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/out")
set(CMAKE_PDB_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/out")

# now that we called project(), load our config variables
macro(cfgcopy _prefix)
	set(${_prefix}_STATIC "${${_prefix}_DEBUG}")
	set(${_prefix}_RELEASESTATIC "${${_prefix}_RELEASE}")
endmacro()
cfgcopy(CMAKE_C_FLAGS)
cfgcopy(CMAKE_CXX_FLAGS)
cfgcopy(CMAKE_SHARED_LINKER_FLAGS)
cfgcopy(CMAKE_STATIC_LINKER_FLAGS)
cfgcopy(CMAKE_EXE_LINKER_FLAGS)

macro(append _var _val)
	set(${_var} "${${_var}} ${_val}")
endmacro()
macro(append2 _var1 _var2 _val)
	append(${_var1} "${_val}")
	append(${_var2} "${_val}")
endmacro()

if(APPLE)
	set(_OSDIR darwin)
	set(_SETVERSION TRUE)
	set(_VERSION "A")

	set(_PLATFORM_LIBS
		-lobjc "-framework Foundation" "-framework AppKit"
	)

	# always use our rpath
	set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
	# the / is required by some older versions of OS X
	set(CMAKE_INSTALL_RPATH "@executable_path/")
	set(CMAKE_MACOSX_RPATH TRUE)
elseif(WIN32)
	set(_OSDIR windows)
	set(_SETVERSION FALSE)

	# note that usp10 comes before gdi32
	# TODO prune this list
	set(_PLATFORM_LIBS
		user32 kernel32 usp10 gdi32 comctl32 uxtheme msimg32 comdlg32 d2d1 dwrite ole32 oleaut32 oleacc uuid
	)
	# and don't include the default libraries
	# note the CACHE FORCE stuff is required here
	set(CMAKE_C_STANDARD_LIBRARIES CACHE STRING "" FORCE)
	set(CMAKE_CXX_STANDARD_LIBRARIES CACHE STRING "" FORCE)

	set(_RESOURCES_RC resources.rc)
else()
	set(_OSDIR unix)
	set(_SETVERSION TRUE)
	set(_VERSION "0")

	find_package(PkgConfig REQUIRED)
	pkg_check_modules(GTK REQUIRED gtk+-3.0)
	string(REPLACE ";" " " _LIBUI_CFLAGS "${GTK_CFLAGS}")
	set(_PLATFORM_LIBS "${GTK_LDFLAGS} -lm -ldl")

	# always use our rpath
	set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
	set(CMAKE_INSTALL_RPATH "\$ORIGIN")
endif()

if(MSVC)
	append2(CMAKE_C_FLAGS CMAKE_CXX_FLAGS
		"/W4 /wd4100 /bigobj /RTC1 /RTCs /RTCu")

	# shut the compiler up in some cases
	# LONGTERM still needed?
	append(CMAKE_CXX_FLAGS " /EHsc")

	append(_LIBUI_CFLAGS " ${_PLATFORM_CFLAGS}")

	# note the /MANIFEST:NO (which must be / and uppercase); thanks FraGag (https://github.com/andlabs/libui/issues/93#issuecomment-223183436)
	# also don't apply to CMAKE_STATIC_LINKER_FLAGS; those are passed to a different tool that doesn't support them
	append2(CMAKE_SHARED_LINKER_FLAGS CMAKE_EXE_LINKER_FLAGS
		" /LARGEADDRESSAWARE /INCREMENTAL:NO /MANIFEST:NO")
else()
	append2(CMAKE_C_FLAGS CMAKE_CXX_FLAGS
		" -Wall -Wextra -pedantic -Wno-unused-parameter -Wno-switch")
	# don't use C_VERSION or CXX_VERSION because they use GNU standards
	append(CMAKE_C_FLAGS " --std=c99")
	append(CMAKE_CXX_FLAGS " --std=c++11")

	if(NOT WIN32)
		append(CMAKE_C_FLAGS_DEBUG " -fPIC")
		append(CMAKE_CXX_FLAGS_DEBUG "  -fPIC")
		append(CMAKE_SHARED_LINKER_FLAGS_DEBUG " -fPIC")
		append(CMAKE_EXE_LINKER_FLAGS_DEBUG " -fPIC")
		append(CMAKE_C_FLAGS_RELEASE " -fPIC")
		append(CMAKE_CXX_FLAGS_RELEASE " -fPIC")
		append(CMAKE_SHARED_LINKER_FLAGS_RELEASE " -fPIC")
		append(CMAKE_EXE_LINKER_FLAGS_RELEASE " -fPIC")
	endif()

	if(WIN32)
		append(_LIBUI_CFLAGS " ${_PLATFORM_CFLAGS}")
	else()
		append(_LIBUI_CFLAGS " -fvisibility=hidden ${_PLATFORM_CFLAGS}")
	endif()

	append(CMAKE_SHARED_LINKER_FLAGS " -fvisibility=hidden")
	# don't amend CMAKE_STATIC_LINKER_FLAGS; that's for ar
endif()

if(NOT _SHARED)
	append(_LIBUI_CFLAGS " -D_UI_STATIC")
endif()

add_subdirectory("common")
add_subdirectory("${_OSDIR}")
if(_SHARED)
	add_library(libui SHARED
		$<TARGET_OBJECTS:libui-common>
		$<TARGET_OBJECTS:libui-${_OSDIR}>
	)
	if(_SETVERSION)
		set_target_properties(libui PROPERTIES
			SOVERSION "${_VERSION}")
	endif()
	target_link_libraries(libui PRIVATE ${_PLATFORM_LIBS})
else()
	_add_static(libui
		$<TARGET_OBJECTS:libui-common>
		$<TARGET_OBJECTS:libui-${_OSDIR}>
	)
endif()
# non-Windows platforms add an extra lib- at the beginning
if(NOT WIN32)
	set_target_properties(libui PROPERTIES
		OUTPUT_NAME ui)
endif()
# let cmake handle quoting and escaping for us
if(WIN32)
	set_target_properties(libui PROPERTIES
		COMPILE_DEFINITIONS "_UI_EXTERN=__declspec(dllexport) extern")
else()
	set_target_properties(libui PROPERTIES
		COMPILE_DEFINITIONS "_UI_EXTERN=__attribute__((visibility(\"default\"))) extern")
endif()

macro(_add_exec _name)
	add_executable(${_name}
		WIN32 EXCLUDE_FROM_ALL
		${ARGN}
		${_RESOURCES_RC})
	target_link_libraries(${_name} libui)
	if(NOT _SHARED)
		target_link_libraries(${_name} ${_PLATFORM_LIBS})
	endif()
endmacro()

add_subdirectory("test")
set_target_properties(tester PROPERTIES
	OUTPUT_NAME test
	WIN32_EXECUTABLE FALSE)

add_subdirectory("examples")
```

What isn't working is

```cmake
if(WIN32)
	set_target_properties(libui PROPERTIES
		COMPILE_DEFINITIONS "_UI_EXTERN=__declspec(dllexport) extern")
```

The definition doesn't show up, causing the DLL not to export anything. What's going on?

**Comment by kainjow** [comment]
Ok, a few points:

- Don't make up new build types. Just go along with the [standard](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html) types. Right now it mentions Static and ReleaseStatic
- Use [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/v3.5/variable/BUILD_SHARED_LIBS.html). Define this as an `option()`, so then the user can set it on the command line like `-DBUILD_SHARED_LIBS=ON`. Then libraries will automatically be SHARED (don't specify STATIC or SHARED in `add_library()`). You can then use `if(BUILD_SHARED_LIBS)` for further customizations.

**Comment by andlabs** [comment]
All right, thanks. I might as well rewrite all this to be more "natural" cmake, and that'd be one of the starting points. Could I make `BUILD_SHARED_LIBS` an `option()`, and if so, do `option()`s go before or after the `project()` line?

**Comment by kainjow** [comment]
I'd put them after. There is very little I've seen needed after `cmake_minimum_required` and before `project()` (or whatever order you prefer those to go, guess it doesn't matter too much).

**Comment by andlabs** [comment]
I'll make a separate issue now that I'm rewriting this.
